### ISSUE TITLE
Lubuntu - No file opening

### ISSUE THREAD

**Issue by njrogie** [lapce/floem#365]
## Behavior
On clicking any of the buttons in `examples/files`, no response is generated and no windows are opened. Instead, an error line is created:
```
thread '<unnamed>' panicked at /home/<username>/.cargo/registry/src/index.crates.io-6f17d22bba15001f/zbus-4.1.2/src/abstractions/executor.rs:189:27:
there is no reactor running, must be called from the context of a Tokio 1.x runtime
```
## Backtrace:
```
0: rust_begin_unwind
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:645:5
   1: core::panicking::panic_fmt
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/panicking.rs:72:14
   2: core::panicking::panic_display
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/panicking.rs:196:5
   3: tokio::runtime::scheduler::Handle::current::panic_cold_display
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/panic.rs:99:13
   4: tokio::runtime::scheduler::Handle::current
             at /home/<user>/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.36.0/src/runtime/scheduler/mod.rs:106:27
   5: tokio::runtime::handle::Handle::current
             at /home/<user>/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.36.0/src/runtime/handle.rs:139:20
   6: tokio::runtime::blocking::pool::spawn_blocking
             at /home/<user>/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.36.0/src/runtime/blocking/pool.rs:182:14
   7: tokio::task::blocking::spawn_blocking
             at /home/<user>/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.36.0/src/task/blocking.rs:209:9
   8: zbus::abstractions::executor::Task<T>::spawn_blocking
             at /home/<user>/.cargo/registry/src/index.crates.io-6f17d22bba15001f/zbus-4.1.2/src/abstractions/executor.rs:189:27
   9: zbus::address::transport::Transport::connect::{{closure}}
             at /home/<user>/.cargo/registry/src/index.crates.io-6f17d22bba15001f/zbus-4.1.2/src/address/transport/mod.rs:103:30
  10: zbus::address::Address::connect::{{closure}}
             at /home/<user>/.cargo/registry/src/index.crates.io-6f17d22bba15001f/zbus-4.1.2/src/address/mod.rs:59:34
  11: zbus::connection::builder::Builder::target_connect::{{closure}}
             at /home/<user>/.cargo/registry/src/index.crates.io-6f17d22bba15001f/zbus-4.1.2/src/connection/builder.rs:505:53
  12: zbus::connection::builder::Builder::build_::{{closure}}
             at /home/<user>/.cargo/registry/src/index.crates.io-6f17d22bba15001f/zbus-4.1.2/src/connection/builder.rs:367:63
  13: zbus::abstractions::executor::Executor::run::{{closure}}
             at /home/<user>/.cargo/registry/src/index.crates.io-6f17d22bba15001f/zbus-4.1.2/src/abstractions/executor.rs:122:20
  14: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/future/future.rs:124:9
  15: zbus::connection::builder::Builder::build::{{closure}}
             at /home/<user>/.cargo/registry/src/index.crates.io-6f17d22bba15001f/zbus-4.1.2/src/connection/builder.rs:357:74
  16: zbus::connection::Connection::session::{{closure}}
             at /home/<user>/.cargo/registry/src/index.crates.io-6f17d22bba15001f/zbus-4.1.2/src/connection/mod.rs:1216:37
  17: ashpd::proxy::Proxy::connection::{{closure}}
             at /home/<user>/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ashpd-0.8.0/src/proxy.rs:39:51
  18: ashpd::proxy::Proxy::new::{{closure}}
             at /home/<user>/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ashpd-0.8.0/src/proxy.rs:65:45
  19: ashpd::proxy::Proxy::new_desktop::{{closure}}
             at /home/<user>/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ashpd-0.8.0/src/proxy.rs:86:65
  20: ashpd::desktop::file_chooser::FileChooserProxy::new::{{closure}}
             at /home/<user>/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ashpd-0.8.0/src/desktop/file_chooser.rs:307:78
  21: ashpd::desktop::file_chooser::OpenFileRequest::send::{{closure}}
             at /home/<user>/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ashpd-0.8.0/src/desktop/file_chooser.rs:468:45
  22: rfd::backend::xdg_desktop_portal::<impl rfd::backend::AsyncFilePickerDialogImpl for rfd::file_dialog::FileDialog>::pick_file_async::{{closure}}
             at /home/<user>/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rfd-0.14.0/src/backend/xdg_desktop_portal.rs:51:18
  23: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/future/future.rs:124:9
  24: pollster::block_on
             at /home/<user>/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pollster-0.3.0/src/lib.rs:128:15
  25: rfd::backend::xdg_desktop_portal::<impl rfd::backend::FilePickerDialogImpl for rfd::file_dialog::FileDialog>::pick_file
             at /home/<user>/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rfd-0.14.0/src/backend/xdg_desktop_portal.rs:33:9
  26: rfd::file_dialog::FileDialog::pick_file
             at /home/<user>/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rfd-0.14.0/src/file_dialog.rs:113:9
  27: floem::action::open_file::{{closure}}
             at /home/<user>/Code/floem/src/action.rs:149:19
```

## System Info
`/etc/os-release`:
PRETTY_NAME="Ubuntu 22.04.4 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.4 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
(LXQt desktop environment)

## Steps to reproduce:
- `cargo run` the files example

**Comment by aalhitennf** [comment]
rfd with tokio (which is default for floem) seems to need the app to run inside multi-threaded runtime, which requires some changes to the example. In the meantime you can switch to async-std in `examples/files/Cargo.toml`:  

`floem = { path = "../..", default-features = false, features = ["rfd-async-std"] }`

**Comment by njrogie** [comment]
Awesome. This works for my purposes. Thanks!
