### ISSUE TITLE
App crashes when quitting while a tooltip is still visible

### ISSUE THREAD

**Issue by dajoha** [lapce/floem#437]
Floem version: https://github.com/lapce/floem/commit/4c2266a9d4466194e17761b374a5f071f14a629e

To reproduce:

```rust
use floem::{
    event::EventListener,
    quit_app,
    views::{container, static_label, tooltip, Decorators},
    View,
};

pub fn app_view() -> impl View {
    container(
        tooltip(static_label("Hello"), || "Tooltip")
    )
        .style(|s| s.size_full())
        .keyboard_navigatable()
        .on_event_stop(EventListener::KeyDown, |_| {
            quit_app();
        })
}

fn main() {
    floem::launch(app_view);
    println!("Bye");
}
```

- hold the mouse over the label to make the tooltip appear;
- while the tooltip is still visible, hit any key to quit the app

Then the final message "Bye" is displayed, and the app panics:

```
Bye
thread 'main' panicked at /rustc/5518eaa946291f00471af8b254b2a1715f234882/library/std/src/thread/local.rs:262:26:
cannot access a Thread Local Storage value during or after destruction: AccessError
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
fatal runtime error: thread local panicked on drop
Abandon (core dumped)
```

Backtrace:

```
   0: rust_begin_unwind
             at /rustc/5518eaa946291f00471af8b254b2a1715f234882/library/std/src/panicking.rs:647:5
   1: core::panicking::panic_fmt
             at /rustc/5518eaa946291f00471af8b254b2a1715f234882/library/core/src/panicking.rs:72:14
   2: core::result::unwrap_failed
             at /rustc/5518eaa946291f00471af8b254b2a1715f234882/library/core/src/result.rs:1649:5
   3: core::result::Result<T,E>::expect
             at /rustc/5518eaa946291f00471af8b254b2a1715f234882/library/core/src/result.rs:1030:23
   4: std::thread::local::LocalKey<T>::with
             at /rustc/5518eaa946291f00471af8b254b2a1715f234882/library/std/src/thread/local.rs:262:9
   5: floem::action::add_update_message
             at .../.cache/.cargo/git/checkouts/floem-69eea0a757d1e3ee/7a52781/src/action.rs:23:5
   6: floem::action::remove_overlay
             at .../.cache/.cargo/git/checkouts/floem-69eea0a757d1e3ee/7a52781/src/action.rs:147:5
   7: <floem::views::tooltip::Tooltip as core::ops::drop::Drop>::drop
             at .../.cache/.cargo/git/checkouts/floem-69eea0a757d1e3ee/7a52781/src/views/tooltip.rs:114:13
   8: core::ptr::drop_in_place<floem::views::tooltip::Tooltip>
             at /rustc/5518eaa946291f00471af8b254b2a1715f234882/library/core/src/ptr/mod.rs:507:1
   9: core::ptr::drop_in_place<alloc::boxed::Box<dyn floem::view::View>>
             at /rustc/5518eaa946291f00471af8b254b2a1715f234882/library/core/src/ptr/mod.rs:507:1
  10: core::ptr::drop_in_place<core::cell::UnsafeCell<alloc::boxed::Box<dyn floem::view::View>>>
             at /rustc/5518eaa946291f00471af8b254b2a1715f234882/library/core/src/ptr/mod.rs:507:1
  11: core::ptr::drop_in_place<core::cell::RefCell<alloc::boxed::Box<dyn floem::view::View>>>
             at /rustc/5518eaa946291f00471af8b254b2a1715f234882/library/core/src/ptr/mod.rs:507:1
  12: <alloc::rc::Rc<T,A> as core::ops::drop::Drop>::drop
             at /rustc/5518eaa946291f00471af8b254b2a1715f234882/library/alloc/src/rc.rs:2100:17
  13: core::ptr::drop_in_place<alloc::rc::Rc<core::cell::RefCell<alloc::boxed::Box<dyn floem::view::View>>>>
             at /rustc/5518eaa946291f00471af8b254b2a1715f234882/library/core/src/ptr/mod.rs:507:1
  14: core::ptr::drop_in_place<slotmap::secondary::Slot<alloc::rc::Rc<core::cell::RefCell<alloc::boxed::Box<dyn floem::view::View>>>>>
             at /rustc/5518eaa946291f00471af8b254b2a1715f234882/library/core/src/ptr/mod.rs:507:1
  15: core::ptr::drop_in_place<[slotmap::secondary::Slot<alloc::rc::Rc<core::cell::RefCell<alloc::boxed::Box<dyn floem::view::View>>>>]>
             at /rustc/5518eaa946291f00471af8b254b2a1715f234882/library/core/src/ptr/mod.rs:507:1
  16: <alloc::vec::Vec<T,A> as core::ops::drop::Drop>::drop
             at /rustc/5518eaa946291f00471af8b254b2a1715f234882/library/alloc/src/vec/mod.rs:3103:13
  17: core::ptr::drop_in_place<alloc::vec::Vec<slotmap::secondary::Slot<alloc::rc::Rc<core::cell::RefCell<alloc::boxed::Box<dyn floem::view::View>>>>>>
             at /rustc/5518eaa946291f00471af8b254b2a1715f234882/library/core/src/ptr/mod.rs:507:1
  18: core::ptr::drop_in_place<slotmap::secondary::SecondaryMap<floem::id::ViewId,alloc::rc::Rc<core::cell::RefCell<alloc::boxed::Box<dyn floem::view::View>>>>>
             at /rustc/5518eaa946291f00471af8b254b2a1715f234882/library/core/src/ptr/mod.rs:507:1
  19: core::ptr::drop_in_place<floem::view_storage::ViewStorage>
             at /rustc/5518eaa946291f00471af8b254b2a1715f234882/library/core/src/ptr/mod.rs:507:1
  20: core::ptr::drop_in_place<core::cell::UnsafeCell<floem::view_storage::ViewStorage>>
             at /rustc/5518eaa946291f00471af8b254b2a1715f234882/library/core/src/ptr/mod.rs:507:1
  21: core::ptr::drop_in_place<core::cell::RefCell<floem::view_storage::ViewStorage>>
             at /rustc/5518eaa946291f00471af8b254b2a1715f234882/library/core/src/ptr/mod.rs:507:1
  22: core::ptr::drop_in_place<core::option::Option<core::cell::RefCell<floem::view_storage::ViewStorage>>>
             at /rustc/5518eaa946291f00471af8b254b2a1715f234882/library/core/src/ptr/mod.rs:507:1
  23: core::mem::drop
             at /rustc/5518eaa946291f00471af8b254b2a1715f234882/library/core/src/mem/mod.rs:992:24
  24: std::sys::pal::common::thread_local::fast_local::destroy_value::{{closure}}
             at /rustc/5518eaa946291f00471af8b254b2a1715f234882/library/std/src/sys/pal/common/thread_local/fast_local.rs:241:9
  25: core::ops::function::FnOnce::call_once
             at /rustc/5518eaa946291f00471af8b254b2a1715f234882/library/core/src/ops/function.rs:250:5
  26: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/5518eaa946291f00471af8b254b2a1715f234882/library/core/src/panic/unwind_safe.rs:272:9
  27: std::panicking::try::do_call
             at /rustc/5518eaa946291f00471af8b254b2a1715f234882/library/std/src/panicking.rs:554:40
  28: __rust_try
  29: std::panicking::try
             at /rustc/5518eaa946291f00471af8b254b2a1715f234882/library/std/src/panicking.rs:518:19
  30: std::panic::catch_unwind
             at /rustc/5518eaa946291f00471af8b254b2a1715f234882/library/std/src/panic.rs:142:14
  31: std::sys::pal::common::thread_local::fast_local::destroy_value
             at /rustc/5518eaa946291f00471af8b254b2a1715f234882/library/std/src/sys/pal/common/thread_local/fast_local.rs:238:21
  32: __call_tls_dtors
  33: <unknown>
  34: exit
  35: <unknown>
  36: __libc_start_main
  37: _start
```

**Comment by dajoha** [comment]
The issue is still present after https://github.com/lapce/floem/commit/9a4c0fa6e1f8412b4a5eb73c8d7f3e0e7dcd9cbc

**Comment by dajoha** [comment]
Finally fixed with https://github.com/lapce/floem/commit/ab28c54124385520972c6d85bc00cb2890c01ff6
