### ISSUE TITLE
Panic when stopping an animation

### ISSUE THREAD

**Issue by meithecatte** [lapce/floem#530]
On current `main`, run `cargo run -p animations`, then click the "Stop" button. This panics with:
```
thread 'main' panicked at src/id.rs:275:18:
already mutably borrowed: BorrowError
```

<details>
<summary>backtrace</summary>

```
   0: rust_begin_unwind
             at /rustc/92c6c03805408a1a261b98013304e9bbf59ee428/library/std/src/panicking.rs:665:5
   1: core::panicking::panic_fmt
             at /rustc/92c6c03805408a1a261b98013304e9bbf59ee428/library/core/src/panicking.rs:74:14
   2: core::cell::panic_already_mutably_borrowed
             at /rustc/92c6c03805408a1a261b98013304e9bbf59ee428/library/core/src/cell.rs:793:5
   3: core::cell::RefCell<T>::borrow
             at /rustc/92c6c03805408a1a261b98013304e9bbf59ee428/library/core/src/cell.rs:980:25
   4: floem::id::ViewId::request_changes
             at ./src/id.rs:275:12
   5: floem::id::ViewId::request_style
             at ./src/id.rs:270:9
   6: floem::window_handle::WindowHandle::process_anim_update_messages
             at ./src/window_handle.rs:1010:25
   7: floem::window_handle::WindowHandle::process_update_no_paint
             at ./src/window_handle.rs:702:13
   8: floem::window_handle::WindowHandle::process_update
             at ./src/window_handle.rs:667:12
   9: floem::window_handle::WindowHandle::event
             at ./src/window_handle.rs:336:9
  10: floem::window_handle::WindowHandle::mouse_input
             at ./src/window_handle.rs:490:17
  11: floem::app_handle::ApplicationHandle::handle_window_event
             at ./src/app_handle.rs:207:17
  12: floem::app::Application::run::{{closure}}
             at ./src/app.rs:151:21
  13: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut
             at /rustc/92c6c03805408a1a261b98013304e9bbf59ee428/library/core/src/ops/function.rs:294:13
  14: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut
             at /rustc/92c6c03805408a1a261b98013304e9bbf59ee428/library/core/src/ops/function.rs:294:13
  15: floem_winit::platform_impl::platform::wayland::event_loop::EventLoop<T>::single_iteration
             at /home/maya/.cargo/registry/src/index.crates.io-6f17d22bba15001f/floem-winit-0.29.4/src/platform_impl/linux/wayland/event_loop/mod.rs:461:13
  16: floem_winit::platform_impl::platform::wayland::event_loop::EventLoop<T>::poll_events_with_timeout
             at /home/maya/.cargo/registry/src/index.crates.io-6f17d22bba15001f/floem-winit-0.29.4/src/platform_impl/linux/wayland/event_loop/mod.rs:323:9
  17: floem_winit::platform_impl::platform::wayland::event_loop::EventLoop<T>::pump_events
             at /home/maya/.cargo/registry/src/index.crates.io-6f17d22bba15001f/floem-winit-0.29.4/src/platform_impl/linux/wayland/event_loop/mod.rs:237:13
  18: floem_winit::platform_impl::platform::wayland::event_loop::EventLoop<T>::run_on_demand
             at /home/maya/.cargo/registry/src/index.crates.io-6f17d22bba15001f/floem-winit-0.29.4/src/platform_impl/linux/wayland/event_loop/mod.rs:201:19
  19: floem_winit::platform_impl::platform::EventLoop<T>::run_on_demand
             at /home/maya/.cargo/registry/src/index.crates.io-6f17d22bba15001f/floem-winit-0.29.4/src/platform_impl/linux/mod.rs:821:56
  20: floem_winit::platform_impl::platform::EventLoop<T>::run
             at /home/maya/.cargo/registry/src/index.crates.io-6f17d22bba15001f/floem-winit-0.29.4/src/platform_impl/linux/mod.rs:814:9
  21: floem_winit::event_loop::EventLoop<T>::run
             at /home/maya/.cargo/registry/src/index.crates.io-6f17d22bba15001f/floem-winit-0.29.4/src/event_loop.rs:249:9
  22: floem::app::Application::run
             at ./src/app.rs:144:17
  23: floem::app::launch
             at ./src/app.rs:34:5
  24: animations::main
             at ./examples/animations/src/main.rs:187:5
  25: core::ops::function::FnOnce::call_once
             at /rustc/92c6c03805408a1a261b98013304e9bbf59ee428/library/core/src/ops/function.rs:250:5
```

</details>

**Comment by jrmoulton** [comment]
the animation system has since been rewritten and this bug is no longer present. Thanks for the report :)
