### ISSUE TITLE
(window-scale) example "windows-scale" is getting an error. It doesn't work on Mac, it doesn't work on Linux.

### ISSUE THREAD

**Issue by YoungHaKim7** [lapce/floem#611]
- Test File
  - https://github.com/YoungHaKim7/rust_GUI_floem_Training/tree/main/Tutorial_Floem/window-scale

- `RUST_BACKTRACE=1 cargo run`
```bash
RUST_BACKTRACE=1 cargo r
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.08s
     Running `target/debug/window-scale`
thread 'main' panicked at /home/g111/.cargo/git/checkouts/floem-69eea0a757d1e3ee/4510c4b/src/context.rs:1263:17:
Tried to access renderer before it was initialized
stack backtrace:
   0: rust_begin_unwind
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/panicking.rs:665:5
   1: core::panicking::panic_fmt
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/panicking.rs:74:14
   2: floem::context::PaintState::renderer_mut
             at /home/gy/.cargo/git/checkouts/floem-69eea0a757d1e3ee/4510c4b/src/context.rs:1263:17
   3: floem::context::PaintState::set_scale
             at /home/gy/.cargo/git/checkouts/floem-69eea0a757d1e3ee/4510c4b/src/context.rs:1274:9
   4: floem::window_handle::WindowHandle::process_update_messages
             at /home/gy/.cargo/git/checkouts/floem-69eea0a757d1e3ee/4510c4b/src/window_handle.rs:922:25
   5: floem::window_handle::WindowHandle::process_update_no_paint
             at /home/gy/.cargo/git/checkouts/floem-69eea0a757d1e3ee/4510c4b/src/window_handle.rs:717:13
   6: floem::window_handle::WindowHandle::process_update
             at /home/gy/.cargo/git/checkouts/floem-69eea0a757d1e3ee/4510c4b/src/window_handle.rs:707:12
   7: floem::app_handle::ApplicationHandle::handle_updates_for_all_windows
             at /home/gy/.cargo/git/checkouts/floem-69eea0a757d1e3ee/4510c4b/src/app_handle.rs:466:13
   8: floem::app_handle::ApplicationHandle::idle
             at /home/gy/.cargo/git/checkouts/floem-69eea0a757d1e3ee/4510c4b/src/app_handle.rs:461:9
   9: floem::app::Application::run
             at /home/gy/.cargo/git/checkouts/floem-69eea0a757d1e3ee/4510c4b/src/app.rs:144:9
  10: floem::app::launch
             at /home/gy/.cargo/git/checkouts/floem-69eea0a757d1e3ee/4510c4b/src/app.rs:32:5
  11: window_scale::main
             at ./src/main.rs:5:5
  12: core::ops::function::FnOnce::call_once
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

- ` RUST_BACKTRACE=full cargo run`
```bash
 RUST_BACKTRACE=full cargo r
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.08s
     Running `target/debug/window-scale`
thread 'main' panicked at /home/g111/.cargo/git/checkouts/floem-69eea0a757d1e3ee/4510c4b/src/context.rs:1263:17:
Tried to access renderer before it was initialized
stack backtrace:
   0:     0x56fe7afa5bf5 - std::backtrace_rs::backtrace::libunwind::trace::h649ab3318d3445c5
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/../../backtrace/src/backtrace/libunwind.rs:116:5
   1:     0x56fe7afa5bf5 - std::backtrace_rs::backtrace::trace_unsynchronized::hf4bb60c3387150c3
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x56fe7afa5bf5 - std::sys::backtrace::_print_fmt::hd9186c800e44bd00
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/sys/backtrace.rs:65:5
   3:     0x56fe7afa5bf5 - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::h1b9dad2a88e955ff
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/sys/backtrace.rs:40:26
   4:     0x56fe7afd02cb - core::fmt::rt::Argument::fmt::h351a7824f737a6a0
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/fmt/rt.rs:173:76
   5:     0x56fe7afd02cb - core::fmt::write::h4b5a1270214bc4a7
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/fmt/mod.rs:1182:21
   6:     0x56fe7afa24df - std::io::Write::write_fmt::hd04af345a50c312d
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/io/mod.rs:1827:15
   7:     0x56fe7afa6ef1 - std::sys::backtrace::BacktraceLock::print::h68d41b51481bce5c
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/sys/backtrace.rs:43:9
   8:     0x56fe7afa6ef1 - std::panicking::default_hook::{{closure}}::h96ab15e9936be7ed
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/panicking.rs:269:22
   9:     0x56fe7afa6bcc - std::panicking::default_hook::h3cacb9c27561ad33
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/panicking.rs:296:9
  10:     0x56fe7afa7551 - std::panicking::rust_panic_with_hook::hfe205f6954b2c97b
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/panicking.rs:800:13
  11:     0x56fe7afa7383 - std::panicking::begin_panic_handler::{{closure}}::h6cb44b3a50f28c44
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/panicking.rs:667:13
  12:     0x56fe7afa60b9 - std::sys::backtrace::__rust_end_short_backtrace::hf1c1f2a92799bb0e
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/sys/backtrace.rs:168:18
  13:     0x56fe7afa7044 - rust_begin_unwind
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/panicking.rs:665:5
  14:     0x56fe790cc953 - core::panicking::panic_fmt::h3d8fc78294164da7
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/panicking.rs:74:14
  15:     0x56fe792c3fd2 - floem::context::PaintState::renderer_mut::h5080ad2dbb7dcc71
                               at /home/gy/.cargo/git/checkouts/floem-69eea0a757d1e3ee/4510c4b/src/context.rs:1263:17
  16:     0x56fe792c406a - floem::context::PaintState::set_scale::hd20a9de556265f25
                               at /home/gy/.cargo/git/checkouts/floem-69eea0a757d1e3ee/4510c4b/src/context.rs:1274:9
  17:     0x56fe79590b18 - floem::window_handle::WindowHandle::process_update_messages::h4bcbc98a1886cfc0
                               at /home/gy/.cargo/git/checkouts/floem-69eea0a757d1e3ee/4510c4b/src/window_handle.rs:922:25
  18:     0x56fe7958f1ab - floem::window_handle::WindowHandle::process_update_no_paint::h4554d22689804218
                               at /home/gy/.cargo/git/checkouts/floem-69eea0a757d1e3ee/4510c4b/src/window_handle.rs:717:13
  19:     0x56fe7958f173 - floem::window_handle::WindowHandle::process_update::he7e7ec7b93b9f0c9
                               at /home/gy/.cargo/git/checkouts/floem-69eea0a757d1e3ee/4510c4b/src/window_handle.rs:707:12
  20:     0x56fe7934272a - floem::app_handle::ApplicationHandle::handle_updates_for_all_windows::h7f0e5cc97f326ba3
                               at /home/gy/.cargo/git/checkouts/floem-69eea0a757d1e3ee/4510c4b/src/app_handle.rs:466:13
  21:     0x56fe7934263b - floem::app_handle::ApplicationHandle::idle::h9878ee5c5e611c0e
                               at /home/gy/.cargo/git/checkouts/floem-69eea0a757d1e3ee/4510c4b/src/app_handle.rs:461:9
  22:     0x56fe7936117a - floem::app::Application::run::heaa5835eb117c884
                               at /home/gy/.cargo/git/checkouts/floem-69eea0a757d1e3ee/4510c4b/src/app.rs:144:9
  23:     0x56fe790eda86 - floem::app::launch::h0b64369495f93c33
                               at /home/gy/.cargo/git/checkouts/floem-69eea0a757d1e3ee/4510c4b/src/app.rs:32:5
  24:     0x56fe790edd76 - window_scale::main::h3738757a8ff8c8ac
                               at /home/gy/my_project/Rust_Lang/111/1111_bevy_avian/Rust_Lang/rust_GUI_floem_Training/Tutorial_Floem/window-scale/src/main.rs:5:5
  25:     0x56fe790d04fb - core::ops::function::FnOnce::call_once::hd6f5822afaeceb78
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/ops/function.rs:250:5
  26:     0x56fe790cfc6e - std::sys::backtrace::__rust_begin_short_backtrace::hbcbaeae4e1cb9c56
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/sys/backtrace.rs:152:18
  27:     0x56fe790e2c01 - std::rt::lang_start::{{closure}}::h7630688ed2ee96f7
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/rt.rs:162:18
  28:     0x56fe7af9a990 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h2feec6363bd28ad6
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/ops/function.rs:284:13
  29:     0x56fe7af9a990 - std::panicking::try::do_call::h71b24ad3a8e797d5
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/panicking.rs:557:40
  30:     0x56fe7af9a990 - std::panicking::try::h8412d1bfb4bcbcc1
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/panicking.rs:521:19
  31:     0x56fe7af9a990 - std::panic::catch_unwind::h2053d3ee5bd8db53
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/panic.rs:350:14
  32:     0x56fe7af9a990 - std::rt::lang_start_internal::{{closure}}::h82eb98fe4f8e75b8
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/rt.rs:141:48
  33:     0x56fe7af9a990 - std::panicking::try::do_call::h793dba66a0bbd3de
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/panicking.rs:557:40
  34:     0x56fe7af9a990 - std::panicking::try::he09b629b3ba06846
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/panicking.rs:521:19
  35:     0x56fe7af9a990 - std::panic::catch_unwind::h7964c913fc871155
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/panic.rs:350:14
  36:     0x56fe7af9a990 - std::rt::lang_start_internal::h5e7c81cecd7f0954
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/rt.rs:141:20
  37:     0x56fe790e2bda - std::rt::lang_start::h977f8664f9420d1b
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/rt.rs:161:17
  38:     0x56fe790edd9e - main
  39:     0x7e6beb22a1ca - __libc_start_call_main
                               at ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
  40:     0x7e6beb22a28b - __libc_start_main_impl
                               at ./csu/../csu/libc-start.c:360:3
  41:     0x56fe790cd4e5 - _start
  42:                0x0 - <unknown>
  ```

- The test environment 
```bash
$ rustc --version --verbose
rustc 1.81.0 (eeb90cda1 2024-09-04)
binary: rustc
commit-hash: eeb90cda1969383f56a2637cbd3037bdf598841c
commit-date: 2024-09-04
host: x86_64-unknown-linux-gnu
release: 1.81.0
LLVM version: 18.1.7



$ bat /etc/*release
───────────────
       │ File: /etc/lsb-release
───────────────
   1   │ DISTRIB_ID=Ubuntu
   2   │ DISTRIB_RELEASE=24.04
   3   │ DISTRIB_CODENAME=noble
   4   │ DISTRIB_DESCRIPTION="Ubuntu 24.04.1 LTS"
───────┴──────────────────
       │ File: /etc/os-release
───────┼──────────────────
   1   │ PRETTY_NAME="Ubuntu 24.04.1 LTS"
   2   │ NAME="Ubuntu"
   3   │ VERSION_ID="24.04"
   4   │ VERSION="24.04.1 LTS (Noble Numbat)"
   5   │ VERSION_CODENAME=noble
   6   │ ID=ubuntu
   7   │ ID_LIKE=debian
   8   │ HOME_URL="https://www.ubuntu.com/"
   9   │ SUPPORT_URL="https://help.ubuntu.com/"
  10   │ BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
  11   │ PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
  12   │ UBUNTU_CODENAME=noble
  13   │ LOGO=ubuntu-logo
```

**Comment by jrmoulton** [comment]
#608 would fix this

**Comment by jrmoulton** [comment]
@YoungHaKim7 #608 was merged. Can you test to see if you still are experiencing the same issue?

**Comment by YoungHaKim7** [comment]
- macOS (M1)
  - It works fine, thank you.

```bash
 OS: macOS Sequoia 15.0.1 arm64
 Host: MacBook Pro (14-inch, 2021)
 Kernel: Darwin 24.0.0
 Uptime: 3 hours, 21 mins
 Packages: 129 (brew), 11 (brew-cask)
 Shell: sh
 Display (U34G3XM): 3440x1440 @ 60 Hz in 34" [External] *
 Display (Color LCD): 3024x1964 @ 60 Hz (as 1512x982) in 14" [Built-in]
 DE: Aqua
 WM: Quartz Compositor
 WM Theme: Multicolor (Light)
 Font: .AppleSystemUIFont [System], Helvetica [User]
 Cursor: Fill - Black, Outline - White (32px)
 Terminal: alacritty 0.13.2
 Terminal Font: Hack Nerd Font (34.0pt)
 CPU: Apple M1 Pro (8) @ 3.23 GHz
 GPU: Apple M1 Pro (14) @ 1.30 GHz [Integrated]
 Memory: 9.33 GiB / 16.00 GiB (58%)
 Swap: Disabled
 Locale: en_US.UTF-8
```

**Comment by YoungHaKim7** [comment]
- Linux OS 
  - It works fine, thank you.
  
```bash
OS: Ubuntu noble 24.04 x86_64
Host: MS-7D42 (2.0)
Kernel: 6.8.0-45-generic
Uptime: 4 mins
Packages: 2521 (dpkg), 9 (snap)
Shell: fish 3.7.1
Display (U34G3XM): 3440x1440 @ 60Hz *
Display (32ML600): 1920x1080 @ 60Hz
DE: Gnome 46.0
 WM: Mutter (X11)
 WM Theme: Yaru
Theme: Yaru [GTK2/3/4]
 Icons: Yaru [GTK2/3/4]
 Font: Ubuntu Sans (11pt) [GTK2/3/4]
Cursor: Yaru (24px)
Terminal: GNOME Terminal 3.52.0
 Terminal Font: Hack Nerd Font (30pt)
 CPU: 13th Gen Intel(R) Core(TM) i5-13600K (20) @ 5.10 GHz
 GPU 1: Intel UHD Graphics 770 @ 1.55 GHz [Integrated]
 GPU 2: NVIDIA GeForce RTX 3060 Ti Lite Hash Rate [Discrete]
 Memory: 3.29 GiB / 94.09 GiB (4%)
 Swap: 0 B / 8.00 GiB (0%)
```

**Comment by YoungHaKim7** [comment]
@jrmoulton It works fine, thank you.
